export const solutions = [
    {
      id: 1,
      Industry: "Farm/Agribusiness\nFood Service\nHotel/Motel",
      Solution: "Wireless Monitoring",
      "Vendor Name": "Quanturi",
      "Example Scenarios": "It is a challenge to control the quality of my hay while being stored.",
      Discount: "5% hardware discount for Nationwide customers",
      Trigger_Words_for_Search: "Farm\nHay\nGrain\nFire\nQuality",
      "Web Link": "https://quanturi.com/",
      "Contact Info": "Name: John Anderson\nPhone: (612) 555-4321\nJanderson@quanturi.ai",
      Logo: "quanturi",
      Description: "Quanturi is the leading provider of wireless temperature monitoring and data analysis solutions for fermentable materials. Quanturi's robust systems are specifically designed to monitor hay, compost, grain and many other fermentable materials during storage. Quanturi systems help to reduce the risk of fire and support the quality control of stored materials."
    },
    {
        id: 2,
        Industry: "Farm/Agribusiness\nFood Service",
        Solution: "Grain Monitoring",
        "Vendor Name": "Quanturi",
        "Example Scenarios": "I am concerned about the risk of grain fires on my farm.",
        Discount: "5% hardware discount for Nationwide customers",
        Trigger_Words_for_Search: "Farm\nHay\nGrain\nFire\nQuality",
        "Contact Info": "Name: John Anderson\nPhone: (612) 555-4321\nJanderson@quanturi.ai",
        "Web Link": "https://quanturi.com/",
        Logo: "quanturi",
        Description: "Quanturi is the leading provider of wireless temperature monitoring and data analysis solutions for fermentable materials. Quanturi's robust systems are specifically designed to monitor hay, compost, grain and many other fermentable materials during storage. Quanturi systems help to reduce the risk of fire and support the quality control of stored materials."
    },
    {
        id: 3,
        Industry: ["Food Service"],
        Solution: "Restaurant Insurance",
        "Vendor Name": "Thimble",
        "Example Scenarios": "I want to purchase insurance for my small business",
        "Contact Info": "Allen Wallace\nPhone: (112) 453-1232\nWallace@thimble.com",
        Discount: "Nationwide customers will receive a 15% discount for bind within 24 hours.",
        Logo: "thimble",
        "Web Link": "https://www.thimble.com/",
        Trigger_Words_for_Search: "Purchase\nProduct\nLiability\nPolicy",
        Description: "Thimble\'s Restaurant Insurance is a type of Business Owners Policy (BOP), which serves up general liability insurance and commercial property insurance in one well-balanced bundle that safeguards small businesses against common risks",
    },
    {
        id: 4,
        Industry: ["Food Service"],
        Solution: "School Cafeteria Refrigeration",
        "Vendor Name": "OneEvent",
        "Example Scenarios": "I am concerned about the temperature fluctuations in my cold storage unit",
        "Contact Info": "Name: Chris Thomas\nPhone: (752) 651-4538\nThomas@oneevent.com",
        Discount: "Nationwide customers will receive free installation on all OneEvent sensors",
        Logo: "oneevent",
        "Web Link": "https://oneeventtech.com/",
        Description: "With OneEvent Refrigeration Monitoring System you can be certain that food is refrigerated at safe temperatures. When temperatures exceed pre-set limits, staff is notified. You will be alerted up to 30 days in advance before a refrigeration unit will fail to keep food safe."
    },
    { //START OF RETAIL SOLUTIONS
        id: 5,
        Industry: ["Retail"],
        Solution: "Electrical Fire Safety",
        "Vendor Name": "Whiskerlabs",
        Logo: "ting",
        "Web Link": "https://www.whiskerlabs.com/",
        Description: "Ting offers a unique and innovative approach to predict potentially hazardous conditions and help prevent disasters before they strike.",
        "Contact Info": "Tim Martin\nPhone: (894) 546-1325\nTim.Martin@whiskerlabs.com",
        Discount: "Nationwide customers will receive a 5% hardware discount.",
        "Example Scenarios": "I am interested in controlling the technology on my premises to make managing my business in a more streamlined fashion.",
        Trigger_Words_for_Search: "Property\nEfficiency\nMonitor"
    },
    {
        id: 6,
        Industry: ["Retail"],
        Solution: "Theft and Vandalism",
        "Vendor Name": "Actuate",
        Logo: "actuate",
          "Web Link": "https://actuate.ai/",
          Description: "Actuate builds software that employs computer vision to automatically detect gun threats, intruders, and liability hazards in security camera feeds.",
          "Contact Info": "Jessa Darrows\nPhone: (911) 546-4651\nDarrows@actuate.ai",
          Discount: "Nationwide customers will receive a 15% dicsount on software monitoring.",
          "Example Scenarios": "I want to be sure that my business is secure.\n\nI want to make sure my employees are safe from violance while working.\n\nI want to reduce hazards that might cause injury to my customers.",
          Trigger_Words_for_Search: "Sensor\nVideo\nSecurity\nCrime\nHazard\nCustomers"
    },
    {
        id: 7,
        Industry: ["Retail"],
        Solution: "Cyber Suite",
        "Vendor Name": "HSB",
        "Example Scenarios": "I am concerned with monitoring my refridgeration systems within my convenience store.\n\nI am interested in monitoring power outages at my place of business while I am not present.",
        Logo: "hsb",
          "Web Link": "https://www.munichre.com/hsb/en.html",
          Description: "HSB can help avoid or reduce the damage to your building or equipment by detecting adverse conditions and then sending an alert, so the hazard can be mitigated prior to a loss.\n\nHSB sensors are ideal for detecting water leaks, frozen pipes, refrigeration failure, high temperature conditions, mold conditions, and power outages.",
          "Contact Info": "Name: Zack Miller\nPhone: (651) 534-8324\nMiller@HSB.com",
          Discount: "Nationwide customers will receive a 5% hardware discount equipment, along with free installation.",
    },
    {
        id: 8,
        Industry: ["Retail", "Hotel/Motel"],
        Solution: "Energy Efficiency",
        "Vendor Name": "HSB",
        "Example Scenarios": "I am concerned with monitoring my refridgeration systems within my convenience store.\n\nI am interested in monitoring power outages at my place of business while I am not present.",
        Description: "Our commercial energy efficiency program customers benefit from both a combination of HSB on-site energy efficiency recommendations...",
        Logo: "hsb",
          "Web Link": "https://www.munichre.com/hsb/en.html",
          "Contact Info": "Name: Zack Miller\nPhone: (651) 534-8324\nMiller@HSB.com",
          Discount: "Nationwide customers will receive a 5% hardware discount equipment, along with free installation.",
    },
    {
        id: 9,
        Industry: ["Retail"],
        Solution: "Retail Banking",
        "Vendor Name": "Floatbot",
        Logo: "floatbot",
          "Web Link": "https://floatbot.ai/",
          Description: "Floatbot is a conversational AI platform that helps businesses increase sales and reduce call volume by automating data collection and customer support, through (hybrid) AI-powered chatbots and voicebots.",
          "Contact Info": "Briane Stein\nPhone: (215) 987-4532",
          Discount: "Nationwide customers will receive a 50% discount when deployed on at least two platforms.",
          "Example Scenarios": "I want my customers to be able to interact with my business digitally.\n\nI want to reduce call volume.\n\nI want to be able to service my customers after business hours.",
          Trigger_Words_for_Search: "Digital\nCalls\nService\nAvailable\nAutomate"
    },
    { //START OF HOTEL/MOTEL
        id: 10,
        Industry: "Hotel/Motel",
        Solution: "Refrigeration Monitoring",
        "Vendor Name": "OneEvent",
        Logo: "oneevent",
          "Web Link": "https://oneeventtech.com/",
          Description: "OneEvent is a sensor technology solution that leverages machine learning to evaluate changes to the environment in which it is positioned. The product has been focused on the early ditection of fire loss.",
          "Contact Info": "Name: Chris Thomas\nPhone: (752) 651-4538\nThomas@oneevent.com",
          Discount: "Nationwide customers will receive free installation on all OneEvent sensors",
          "Example Scenarios": "I am interested in monitoring the sensors on my premises to make managing my business more streamlined.",
          Trigger_Words_for_Search: "Cooking\nBuilding"
    },
    {
        id: 11,
        Industry: ["Hotel/Motel"],
        Solution: "Injury Reduction",
        "Vendor Name": "Wearkinetic",
        Logo: "kinetic",
          "Web Link": "https://www.wearkinetic.com/",
          Description: "Wearable devices and software that gather data and offer reminders to workers when the devices sense high-risk montions that could potentially cause injury.",
          "Contact Info": "Walker Lane\nPhone: (944) 235-7788\nWalker@Kinetic.com",
          Discount: "Nationwide customers will receive a 10% discount on Kinetic hardware.",
          "Example Scenarios": "I want to make sure my employees are not injured.\n\nI want to be sure my business environment is safe for my workers.\n\nI want to make corrections to my facility that might cause injury.",
          Trigger_Words_for_Search: "Sensor\nWorker\nRisk\nMotion\nInjury"
    },
    { //FARM AGRIBUSINESS
        id: 12,
        Industry: ["Farm/Agribusiness"],
        Solution: "Farm Monitoring",
        "Vendor Name": "Quanturi",
        Logo: "quanturi",
          "Web Link": "https://quanturi.com/",
          Description: "Quanturi is the leading provider of wireless temperature monitoring and data analysis solutions for fermentable materials. Quanturi's robust systems are specifically designed to monitor hay, compost, grain and many other fermentable materials during storage. Quanturi systems help to reduce the risk of fire and support the quality control of stored materials.",
          "Contact Info": "Name: John Anderson\nPhone: (612) 555-4321\nJanderson@quanturi.ai",
          Discount: "5% hardware discount for Nationwide customers",
          "Example Scenarios": "I am concerned about the risk of grain fires on my farm.\n\nIt is a challenge to control the quality of my hay while being stored.",
          Trigger_Words_for_Search: "Farm\nHay\nGrain\nFire\nQuality"
    },
    {
        id: 13,
        Industry: ["Farm/Agribusiness"],
        Solution: "Grain Monitoring",
        "Vendor Name": "CropZilla",
        Logo: "cropzilla",
          "Web Link": "https://cropzilla.com/",
          Description: "CropZilla uses sensor technology to track equipment performance, helping the farmer to optimize operations based on cost and timeliness.",
          "Contact Info": "Name: Spencer Smith\nPhone: (330) 555-8557\nSpencers@cropzilla.com",
          Discount: "Nationwide customers will receive a 20% discount on first year of software subscription",
          "Example Scenarios": "It is difficult to understand where costs are being incurred on my farm.\n\nIt is difficult to project the cost of maintaining my farm in future years.",
          Trigger_Words_for_Search: "Farm\nCost\nMonitor\nControl\nDetect"
    },
    {
        id: 14,
        Industry: ["Farm/Agribusiness"],
        Solution: "Fleet Management",
        "Vendor Name": "Razor Tracking",
        Logo: "razortracking",
          "Web Link": "https://razortracking.com/",
          Description: "Dash cameras developed to provide evidence of events leading up to and during road traffic accidents. The cameras provide instant notifications and video in less than a minute, allowing for driver coaching and assistance in claims handling.",
          "Contact Info": "Joe Scarben\nPhone: (854) 555-8934\nScarben@razortracking.com",
          Discount: "Nationwide customers will receive a 10% discount for participating in the Razor Tracking program.",
          "Example Scenarios": "I am interested in tracking my assets and associates as they manage my business's vehicles and equipment.\n\nI want to be sure that my associates are driving safely.",
          Trigger_Words_for_Search: "Track\nSpeed\nVehicle\nEquipment\nAlert"
    },
    {
        id: 15,
        Industry: ["Farm/Agribusiness"],
        Solution: "Fire Prevention",
        "Vendor Name": "PrevTech",
        Logo: "prevtech",
          "Web Link": "https://www.prevtech.ca/",
          Description: "Prev Tech continuously monitors the condition of electrical networks, detecting and diagnosing abnormalities and potential problems in real time, allowing losses to be avoided entirely.",
          "Contact Info": "Michael Burns\nPhone: (899) 551-4563\nMburns@prevtech.com",
          Discount: "Nationwide customers will receive a 25% annual discount on software monitoring.",
          "Example Scenarios": "I am interested in controlling the technology on my premises to manage my business in a more streamlined fashion.",
          Trigger_Words_for_Search: "Monitor\nElectrical\nEfficiency\nProblems"
    },
    {
        id: 16,
        Industry: ["Farm/Agribusiness"],
        Solution: "Temperature Sensor",
        "Vendor Name": "BassAgritech Temprevent",
        Logo: "bassagritech",
          "Web Link": "https://www.bassagritech.com/temprevent",
          Description: "Temperature sensors detect overheating bearings or other components before any major issues can be caused. Sensors can fit in much tighter places and last longer than the most advanced temperature sensors currently on the market.",
          "Contact Info": "Luke Allen\nPhone: (895)541-8974\nLAS@bassagritech.com",
          Discount: "Nationwide customers will receive a 15% hardware discount and free installation.",
          "Example Scenarios": "I am interested in avoiding overheating of my equipment.\n\nI am concerned about machinery fires.",
          Trigger_Words_for_Search: "Machinery\nEquipment\nFire\nTemperature\nSensor"
    },
    {
        id: 17,
        Industry: ["Farm/Agribusiness"],
        Solution: "Fire Supression",
        "Vendor Name": "Stripper Saver",
        Logo: "strippersaver",
          "Web Link": "https://www.facebook.com/Stripper-Saver-806-759-0649-735080730030510/",
          Description: "Fire suppression systems designed specifically for John Deere Cotton Strippers.",
          "Contact Info": "Michael Gary\nPhone: (221) 891-5432\nMGary@Stripper-Saver.com",
          Discount: "Nationwide customers will receive a 5% discount.",
          "Example Scenarios": "I am interested in avoiding overheating of my equipment.\n\nI am concerned about machinery fires.",
          Trigger_Words_for_Search: "Fire\nStripper\nJohn Deere"
    },
    {
        id: 18,
        Industry: ["Farm/Agribusiness"],
        Solution: "Fleet Optimization",
        "Vendor Name": "EquipmentShare",
        Logo: "estrack",
          "Web Link": "https://www.equipmentshare.com/t3",
          Description: "ES Track offers telematics and hardware technology to monitor equipment health, software to optimize rental utilization, and mobile applications for team members to clock in and off on the spot. ES Track integrates with existing software systems to digitize a business's manual processes.",
          "Contact Info": "Jacob Ryan\nPhone: (899)123-8452\nJR@equipmentshare.com",
          Discount: "Nationwide customers will receive a 15% discount on hardware monitoring.",
          "Example Scenarios": "I am interested in tracking my assets and associates as they manage my business's vehicles and equipment.",
          Trigger_Words_for_Search: "Vehicles\nEquipment\nSensor\nMonitor\nTrack"
    },
    {
        id: 19,
        Industry: ["Farm/Agribusiness"],
        Solution: "InfraDrone",
        "Vendor Name": "Infralytiks",
        Logo: "infralytics",
          "Web Link": "https://infralytiks.com/",
          Description: "InfraLytiks is an engineering and data analytics company that uses machine learning, artificial intelligence, and computer vision to automate complex processes and detect internal building hazards.",
          "Contact Info": "Gracelyn Hart\nPhone: (214) 321-7892\nGracelyn@infralytiks.com",
          Discount: "Nationwide customers will receive a 10% discount on annual software monitoring.",
          "Example Scenarios": "I want to detect the potential for fire inside my buildings.",
          Trigger_Words_for_Search: "Fire\nBuilding\nFarm"
    },
    { //HABITATIONAL
        id: 20,
        Industry: ["Habitational"],
        Solution: "Operational Property",
        "Vendor Name": "HSB",
        Logo: "hsb",
          "Web Link": "https://www.munichre.com/hsb/en.html",
          Description: "HSB can help avoid or reduce the damage to your building or equipment by detecting adverse conditions and then sending an alert, so the hazard can be mitigated prior to a loss.\n\nHSB sensors are ideal for detecting water leaks, frozen pipes, refrigeration failure, high temperature conditions, mold conditions, and power outages.",
          "Contact Info": "Name: Zack Miller\nPhone: (651) 534-8324\nMiller@HSB.com",
          Discount: "Nationwide customers will receive a 5% hardware discount equipment, along with free installation.",
          "Example Scenarios": "I am interested in monitoring power outages at my place of business while I am not present.",
          Trigger_Words_for_Search: "Systems\nPower\nSensor\nWater\nPipes\nTemperature"
    },
    {
        id: 21,
        Industry: ["Habitational"],
        Solution: "Motion Sensors",
        "Vendor Name": "OneEvent",
        Logo: "oneevent",
          "Web Link": "https://oneeventtech.com/",
          Description: "OneEvent is a sensor technology solution that leverages machine learning to evaluate changes to the environment in which it is positioned. The product has been focused on the early ditection of fire loss.",
          "Contact Info": "Name: Chris Thomas\nPhone: (752) 651-4538\nThomas@oneevent.com",
          Discount: "Nationwide customers will receive free installation on all OneEvent sensors",
          "Example Scenarios": "I am interested in monitoring the sensors on my premises to make managing my business more streamlined.",
          Trigger_Words_for_Search: "Building"
    },
    {
        id: 22,
        Industry: ["Habitational"],
        Solution: "Fire Hazard Sensor",
        "Vendor Name": "Whiskerlabs",
        Logo: "ting",
          "Web Link": "https://www.whiskerlabs.com/",
          Description: "Ting offers a unique and innovative approach to predict potentially hazardous conditions and help prevent disasters before they strike.",
          "Contact Info": "Tim Martin\nPhone: (894) 546-1325\nTim.Martin@whiskerlabs.com",
          Discount: "Nationwide customers will receive a 5% hardware discount.",
          "Example Scenarios": "I am interested in controlling the technology on my premises to make managing my business in a more streamlined fashion.",
          Trigger_Words_for_Search: "Property\nEfficiency\nMonitor"
    },
    {
        id: 23,
        Industry: ["Habitational"],
        Solution: "Thermal Roof Inspection",
        "Vendor Name": "Infralytiks",
        Logo: "infralytics",
          "Web Link": "https://infralytiks.com/",
          Description: "InfraLytiks is an engineering and data analytics company that uses machine learning, artificial intelligence, and computer vision to automate complex processes and detect internal building hazards.",
          "Contact Info": "Gracelyn Hart\nPhone: (214) 321-7892\nGracelyn@infralytiks.com",
          Discount: "Nationwide customers will receive a 10% discount on annual software monitoring.",
          "Example Scenarios": "I want to detect the potential for fire inside my buildings.",
          Trigger_Words_for_Search: "Fire\nBuilding\nFarm"
    },
    {
        id: 24,
        Industry: ["Habitational"],
        Solution: "Address-Level Analytics",
        "Vendor Name": "Cape Analytics",
        Logo: "capeanalytics",
          "Web Link": "https://capeanalytics.com/",
          Description: "Cape Analytics uses deep learning and geospatial imagery to provide instant property intelligence for buildings, including property defects and potential exposures.",
          "Contact Info": "Cameron Beacher\nPhone: (863) 498-1235\nBeacher@capeanalytics.com",
          Discount: "Nationwide customers will receive an annual 10% discount on software monitoring",
          "Example Scenarios": "I want to avoid losses to my buildings.\n\nI want to detect problems that need to be fixed on my properties.",
          Trigger_Words_for_Search: "Imagery\nSatellite\nBuilding\nDamage\nHazard"
    }
];