export const vendors = [
  {
    "Industry": "Farm/Agribusiness",
    "Vendor Name": "Quanturi",
    "Products": "Grain Temperature Monitoring\nHay Temperature Monitoring\nCompost Temperature Monitoring",
    "Logo": "quanturi",
    "Web Link": "https://quanturi.com/",
    "Description": "Quanturi is the leading provider of wireless temperature monitoring and data analysis solutions for fermentable materials. Quanturi's robust systems are specifically designed to monitor hay, compost, grain and many other fermentable materials during storage. Quanturi systems help to reduce the risk of fire and support the quality control of stored materials.",
    "Contact Info": "Name: John Anderson\nPhone: (612) 555-4321\nJanderson@quanturi.ai",
    "Discount": "5% hardware discount for Nationwide customers",
    "Example Scenarios": "I am concerned about the risk of grain fires on my farm.\n\nIt is a challenge to control the quality of my hay while being stored.",
    "Trigger Words for Search": "Farm\nHay\nGrain\nFire\nQuality"
  },
  {
    "Industry": "Farm/Agribusiness",
    "Vendor Name": "CropZilla",
    "Products": "Farm Machine Analytics\nFarm Enterprise Software",
    "Logo": "cropzilla",
    "Web Link": "https://cropzilla.com/",
    "Description": "CropZilla uses sensor technology to track equipment performance, helping the farmer to optimize operations based on cost and timeliness.",
    "Contact Info": "Name: Spencer Smith\nPhone: (330) 555-8557\nSpencers@cropzilla.com",
    "Discount": "Nationwide customers will receive a 20% discount on first year of software subscription",
    "Example Scenarios": "It is difficult to understand where costs are being incurred on my farm.\n\nIt is difficult to project the cost of maintaining my farm in future years.",
    "Trigger Words for Search": "Farm\nCost\nMonitor\nControl\nDetect"
  },
  {
    "Industry": "Farm/Agribusiness\nFood Service\nHabitational\nHotel/Motel",
    "Vendor Name": "OneEvent",
    "Products": "Temperature Monitoring\nRefrigeration Monitoring",
    "Logo": "oneevent",
    "Web Link": "https://oneeventtech.com/",
    "Description": "OneEvent is a sensor technology solution that leverages machine learning to evaluate changes to the environment in which it is positioned. The product has been focused on the early ditection of fire loss.",
    "Contact Info": "Name: Chris Thomas\nPhone: (752) 651-4538\nThomas@oneevent.com",
    "Discount": "Nationwide customers will receive free installation on all OneEvent sensors",
    "Example Scenarios": "I am interested in monitoring the sensors on my premises to make managing my business more streamlined.",
    "Trigger Words for Search": "Fire\nCooking\nBuilding"
  },
  {
    "Industry": "Food Service\nRetail\nHotel/Motel\nHabitational\nProcess/Service\nManufacturing\nAuto Service\nWholesale\nConstruction\nOffice/Professional\nHealth Care\nFarm/Agribusiness",
    "Vendor Name": "HSB",
    "Products": "IoT Commercial Sensor Solutions\nIoT Industrial Sensor Solutions\nIoT Residential Sensor Solutions",
    "Logo": "hsb",
    "Web Link": "https://www.munichre.com/hsb/en.html",
    "Description": "HSB can help avoid or reduce the damage to your building or equipment by detecting adverse conditions and then sending an alert, so the hazard can be mitigated prior to a loss.\n\nHSB sensors are ideal for detecting water leaks, frozen pipes, refrigeration failure, high temperature conditions, mold conditions, and power outages.",
    "Contact Info": "Name: Zack Miller\nPhone: (651) 534-8324\nMiller@HSB.com",
    "Discount": "Nationwide customers will receive a 5% hardware discount equipment, along with free installation.",
    "Example Scenarios": "I am concerned with monitoring my refridgeration systems within my convenience store.\n\nI am interested in monitoring power outages at my place of business while I am not present.",
    "Trigger Words for Search": "Refridgeration\nSystems\nPower\nSensor\nWater\nPipes\nTemperature"
  },
  {
    "Industry": "Farm/Agribusiness\nConstruction",
    "Vendor Name": "Zubie",
    "Products": "Asset Tracking\nDashcam",
    "Logo": "zubie",
    "Web Link": "https://zubie.com/asset-trak/",
    "Description": "Asset tracking that speeds the time to recover lost or stollen assets with previous locations, device tamper alerts, and location information. Detailed location history lets users monitor how and where assets are being used.",
    "Contact Info": "Bob Mueller\nPhone: (568) 321-8537\nBM@Zubie.com",
    "Discount": "50% device discount for Nationwide customers",
    "Example Scenarios": "I am interested in tracking my assets and associates as they manage my equipment.",
    "Trigger Words for Search": "Equipment\nMonitor\nTracking"
  },
  {
    "Industry": "Farm/Agribusiness\nFood Service\nHealth Care\nWholesale\nRetail",
    "Vendor Name": "Razor Tracking",
    "Products": "Asset Tracking\nVehicle Tracking,Dashcam",
    "Logo": "razortracking",
    "Web Link": "https://razortracking.com/",
    "Description": "Dash cameras developed to provide evidence of events leading up to and during road traffic accidents. The cameras provide instant notifications and video in less than a minute, allowing for driver coaching and assistance in claims handling.",
    "Contact Info": "Joe Scarben\nPhone: (854) 555-8934\nScarben@razortracking.com",
    "Discount": "Nationwide customers will receive a 10% discount for participating in the Razor Tracking program.",
    "Example Scenarios": "I am interested in tracking my assets and associates as they manage my business's vehicles and equipment.\n\nI want to be sure that my associates are driving safely.",
    "Trigger Words for Search": "Track\nSpeed\nVehicle\nEquipment\nAlert"
  },
  {
    "Industry": "Farm/Agribusiness\nHabitational\nFood Service\nHotel/Motel",
    "Vendor Name": "PrevTech",
    "Products": "Electrical Fire Detection",
    "Logo": "prevtech",
    "Web Link": "https://www.prevtech.ca/",
    "Description": "Prev Tech continuously monitors the condition of electrical networks, detecting and diagnosing abnormalities and potential problems in real time, allowing losses to be avoided entirely.",
    "Contact Info": "Michael Burns\nPhone: (899) 551-4563\nMburns@prevtech.com",
    "Discount": "Nationwide customers will receive a 25% annual discount on software monitoring.",
    "Example Scenarios": "I am interested in controlling the technology on my premises to manage my business in a more streamlined fashion.",
    "Trigger Words for Search": "Monitor\nElectrical\nEfficiency\nProblems"
  },
  {
    "Industry": "Farm/Agribusiness\nHabitational\nRetail\nFood Service",
    "Vendor Name": "Ting",
    "Products": "Electrical Fire Detection",
    "Logo": "ting",
    "Web Link": "https://www.whiskerlabs.com/",
    "Description": "Ting offers a unique and innovative approach to predict potentially hazardous conditions and help prevent disasters before they strike.",
    "Contact Info": "Tim Martin\nPhone: (894) 546-1325\nTim.Martin@whiskerlabs.com",
    "Discount": "Nationwide customers will receive a 5% hardware discount.",
    "Example Scenarios": "I am interested in controlling the technology on my premises to make managing my business in a more streamlined fashion.",
    "Trigger Words for Search": "Property\nEfficiency\nMonitor"
  },
  {
    "Industry": "Farm/Agribusiness",
    "Vendor Name": "BassAgritech Temprevent",
    "Products": "Farm Machine Overheating Detection",
    "Logo": "bassagritech",
    "Web Link": "https://www.bassagritech.com/temprevent",
    "Description": "Temperature sensors detect overheating bearings or other components before any major issues can be caused. Sensors can fit in much tighter places and last longer than the most advanced temperature sensors currently on the market.",
    "Contact Info": "Luke Allen\nPhone: (895)541-8974\nLAS@bassagritech.com",
    "Discount": "Nationwide customers will receive a 15% hardware discount and free installation.",
    "Example Scenarios": "I am interested in avoiding overheating of my equipment.\n\nI am concerned about machinery fires.",
    "Trigger Words for Search": "Machinery\nEquipment\nFire\nTemperature\nSensor"
  },
  {
    "Industry": "Farm/Agribusiness",
    "Vendor Name": "Stripper Saver",
    "Products": "Cotton Stripper Fire Supression",
    "Logo": "strippersaver",
    "Web Link": "https://www.facebook.com/Stripper-Saver-806-759-0649-735080730030510/",
    "Description": "Fire suppression systems designed specifically for John Deere Cotton Strippers.",
    "Contact Info": "Michael Gary\nPhone: (221) 891-5432\nMGary@Stripper-Saver.com",
    "Discount": "Nationwide customers will receive a 5% discount.",
    "Example Scenarios": "I am interested in avoiding overheating of my equipment.\n\nI am concerned about machinery fires.",
    "Trigger Words for Search": "Fire\nStripper\nJohn Deere"
  },
  {
    "Industry": "Farm/Agribusiness\nManufacturing",
    "Vendor Name": "Argus",
    "Products": "Infrared Spark Detection\nFire Supression",
    "Logo": "argus",
    "Web Link": "http://argusfirecontrol.com/Products.html",
    "Description": "Argus Fire Control specializes in the design, manufacture, and service of industrial production protection systems for fire hazards as well as metal detection and diverting. Argus Fire Control offers engineered systems for the textile spinning and non-woven industry as well as for wood-working, cotton gins, recycling, and other industrial applications.",
    "Contact Info": "Owen Beckett\nPhone: (465) 548-5435\nOBP@ argusfirecontrol.com",
    "Discount": "Nationwide customers will receive a 20% discount on Argus hardware.",
    "Example Scenarios": "I need assistance maintaining my production systems.\n\nI am interested in fire control of my industrial systems.",
    "Trigger Words for Search": "Fire\nIndustrial\nDetect\nManufacturing"
  },
  {
    "Industry": "Construction\nFarm/Agribusiness",
    "Vendor Name": "ES Track",
    "Products": "Asset Tracking\nVehicle Tracking\nDashcam\nFleet Management",
    "Logo": "estrack",
    "Web Link": "https://www.equipmentshare.com/t3",
    "Description": "ES Track offers telematics and hardware technology to monitor equipment health, software to optimize rental utilization, and mobile applications for team members to clock in and off on the spot. ES Track integrates with existing software systems to digitize a business's manual processes.",
    "Contact Info": "Jacob Ryan\nPhone: (899)123-8452\nJR@equipmentshare.com",
    "Discount": "Nationwide customers will receive a 15% discount on hardware monitoring.",
    "Example Scenarios": "I am interested in tracking my assets and associates as they manage my business's vehicles and equipment.",
    "Trigger Words for Search": "Vehicles\nEquipment\nSensor\nMonitor\nTrack"
  },
  {
    "Industry": "Food Service\nRetail\nHotel/Motel\nProcess/Service\nManufacturing\nAuto Service\nWholesale\nConstruction\nHealth Care\nFarm/Agribusiness",
    "Vendor Name": "Kinetic",
    "Products": "Wearable Injury Prevention",
    "Logo": "kinetic",
    "Web Link": "https://www.wearkinetic.com/",
    "Description": "Wearable devices and software that gather data and offer reminders to workers when the devices sense high-risk montions that could potentially cause injury.",
    "Contact Info": "Walker Lane\nPhone: (944) 235-7788\nWalker@Kinetic.com",
    "Discount": "Nationwide customers will receive a 10% discount on Kinetic hardware.",
    "Example Scenarios": "I want to make sure my employees are not injured.\n\nI want to be sure my business environment is safe for my workers.\n\nI want to make corrections to my facility that might cause injury.",
    "Trigger Words for Search": "Sensor\nWorker\nRisk\nMotion\nInjury"
  },
  {
    "Industry": "Manufacturing\nProcess/Service\nConstruction\nFarm/Agribusiness",
    "Vendor Name": "MakUSafe",
    "Products": "Wearable Injury Prevention",
    "Logo": "makeusafe",
    "Web Link": "https://makusafe.com/?gclid=Cj0KCQiA5aWOBhDMARIsAIXLlkfnfBX6FZkNnPAPgq8J4DkIWSUFFts4Lav2d7ZSkQeGVY-KjAbig_0aApqIEALw_wcB",
    "Description": "The MakuSafe dashboard displays data from connected factory equipment and systems, providing insights and context into employee health safety concerns. Devices send data from each worker the business's platforms, creating opportunities to enhance operations and reduce workplace hazards.",
    "Contact Info": "Sydney Kendall\nPhone: (635) 567-8922\nSydney@makusafe.com",
    "Discount": "Nationwide customers will receive hardware installation and training at no cost.",
    "Example Scenarios": "I want to make sure my employees are not injured.\n\nI want to be sure my business environment is safe for my workers.\n\nI want to make corrections to my facility that might cause injury.",
    "Trigger Words for Search": "Sensor\nWorker\nRisk\nMotion\nInjury\nEnvironment"
  },
  {
    "Industry": "Habitational\nFarm/Agribusiness\nManufacturing\nConstruction",
    "Vendor Name": "InfraLytiks",
    "Products": "Data Analytics",
    "Logo": "infralytics",
    "Web Link": "https://infralytiks.com/",
    "Description": "InfraLytiks is an engineering and data analytics company that uses machine learning, artificial intelligence, and computer vision to automate complex processes and detect internal building hazards.",
    "Contact Info": "Gracelyn Hart\nPhone: (214) 321-7892\nGracelyn@infralytiks.com",
    "Discount": "Nationwide customers will receive a 10% discount on annual software monitoring.",
    "Example Scenarios": "I want to detect the potential for fire inside my buildings.",
    "Trigger Words for Search": "Fire\nBuilding\nFarm"
  },
  {
    "Industry": "Habitational\nConstruction",
    "Vendor Name": "Cape Analytics",
    "Products": "Data Analytics",
    "Logo": "capeanalytics",
    "Web Link": "https://capeanalytics.com/",
    "Description": "Cape Analytics uses deep learning and geospatial imagery to provide instant property intelligence for buildings, including property defects and potential exposures.",
    "Contact Info": "Cameron Beacher\nPhone: (863) 498-1235\nBeacher@capeanalytics.com",
    "Discount": "Nationwide customers will receive an annual 10% discount on software monitoring",
    "Example Scenarios": "I want to avoid losses to my buildings.\n\nI want to detect problems that need to be fixed on my properties.",
    "Trigger Words for Search": "Imagery\nSatellite\nBuilding\nDamage\nHazard"
  },
  {
    "Industry": "Habitational\nFood Service\nRetail \nProcess Service\nOffice/Professional",
    "Vendor Name": "Senseware",
    "Products": "IoT Commercial Environment Sensor Monitoring",
    "Logo": "senseware",
    "Web Link": "https://www.senseware.co/",
    "Description": "Senseware is a wireless sensor-based system that communicates physical asset data on a real-time basis to help promote energy efficiency and sustainability. Senseware uses smart sensors, wireless communication, the internet, and cloud-based technology to ‘connect the unconnected’and create Intelligent communities.",
    "Contact Info": "Gia Mead\nPhone: (544)936-4512\nMead@senseware.co",
    "Discount": "Nationwide customers will receive free installation on all Senseware hardware.",
    "Example Scenarios": "It is difficult to understand where costs are being incurred at my business.\n\nI am interested in monitoring the sensors on my premises to make managing my business more streamlined.",
    "Trigger Words for Search": "Sensor\nData\nMonitor\nEfficiency"
  },
  {
    "Industry": "Retail\nFood Service\nProfess/Service\nHabitational\nOffice/Professional",
    "Vendor Name": "Deep Sentinel",
    "Products": "Home Security Cameras",
    "Logo": "deepsentinel",
    "Web Link": "https://www.deepsentinel.com/",
    "Description": "Deep Sentinel is a home security company that produces a series of cameras powered by deep learning that can evaluate threats on a property.",
    "Contact Info": "Peter Flynn\nPhone: (912) 453-7532\nFlynn@deepsentinel.com",
    "Discount": "Nationwide customers will receive free hardeware and  one year of software monitoring.",
    "Example Scenarios": "I want to be sure that my business is secure.\n\nI want to make sure my employees are safe from violance while working.",
    "Trigger Words for Search": "Sensor\nVideo\nSecurity\nCrime"
  },
  {
    "Industry": "Retail\nHotel/Motel\nProcess/Service\nAuto Service\nOffice/Professional",
    "Vendor Name": "Cogito",
    "Products": "AI coaching system for the contact center",
    "Logo": "cogito",
    "Web Link": "https://cogitocorp.com/",
    "Description": "Cogito enhances the emotional intelligence of phone professionals by applying behavioral science through artificial intelligence.",
    "Contact Info": "Vick Ricky\nPhone: (744) 456-4211\nVick@Cogito.com",
    "Discount": "Nationtide customers will receive complimentary training and software monitoring on Cogito software.",
    "Example Scenarios": "I want to be sure my employees are delivering the best customer experience possible.\n\nI want to help teach my employees how to be good customer service representatives.",
    "Trigger Words for Search": "Customer service\nMonitor\nTeach\nBehavior"
  },
  {
    "Industry": "Health Care\nHabitational",
    "Vendor Name": "Care Predict",
    "Products": "Wearable for Aged Care",
    "Logo": "carepredict",
    "Web Link": "https://www.carepredict.com/",
    "Description": "CarePredict technology continuously observes, learns, and triggers just in time care for aging seniors. The technology is ideal for group living, home care, and senior centers.",
    "Contact Info": "Tom Townsie\nPhone: (894) 112-4882\nTownsie@carepredict.com",
    "Discount": "Nationwide customers will receive a 5% hardware discount, along with associate training.",
    "Example Scenarios": "I want to take care of the patients at my facility.\n\nI want to help track the movements and locations of patients.\n\nI want to avoid patient and worker injury.",
    "Trigger Words for Search": "Senior care\nAssisted living\nNursing home\nPatients\nInjury\nTracking"
  },
  {
    "Industry": "Construction\nFood Service\nProcess/Service\nAuto Service\nHealth Care",
    "Vendor Name": "Thimble",
    "Products": "GIG Liability Insurance",
    "Logo": "thimble",
    "Web Link": "https://www.thimble.com/",
    "Description": "Thimble provides liability coverage for customers in more than 100 professions including landscapers, beauticians, dog walkers, handymen, DJs, and musicians. The flexible coverage platform offers short term, versatile insurance to small businesses, independent workers, and freelancers.",
    "Contact Info": "Allen Wallace\nPhone: (112) 453-1232\nWallace@thimble.com",
    "Discount": "Nationwide customers will receive a 15% discount for bind within 24 hours.",
    "Example Scenarios": "I want to purchase insurance for my small business.",
    "Trigger Words for Search": "Purchase\nProduct\nLiability\nPolicy"
  },
  {
    "Industry": "Food Service\nRetail\nHotel/Motel\nProcess/Service\nAuto Service\nOffice/Professional",
    "Vendor Name": "ServiceBOT",
    "Products": "Low-Code Chat Bot Building Tools",
    "Logo": "servicebot",
    "Web Link": "https://servisbot.com/",
    "Description": "A conversational AI platform that provides a number of low-code and no-code tools that enable business users to easily design, build, and manage conversational AI experiences.",
    "Contact Info": "Jimmie Bond\nPhone: (235) 215-4621\nBond@ServiceBOT.com",
    "Discount": "Nationwide customerw siwll receive a 20% discount when engaging to build BOT technology, bringing to production.",
    "Example Scenarios": "I want my customers to be able to interact with my business digitally.\n\nI want to reduce call volume.\n\nI want to be able to service my customers after business hours.",
    "Trigger Words for Search": "Digital\nCalls\nService\nAvailable\nAutomate"
  },
  {
    "Industry": "Food Service\nRetail\nProcess/Service\nAuto Service\nConstruction\nHealth Care",
    "Vendor Name": "Actuate",
    "Products": "Computer Vision Hazard Detection",
    "Logo": "actuate",
    "Web Link": "https://actuate.ai/",
    "Description": "Actuate builds software that employs computer vision to automatically detect gun threats, intruders, and liability hazards in security camera feeds.",
    "Contact Info": "Jessa Darrows\nPhone: (911) 546-4651\nDarrows@actuate.ai",
    "Discount": "Nationwide customers will receive a 15% dicsount on software monitoring.",
    "Example Scenarios": "I want to be sure that my business is secure.\n\nI want to make sure my employees are safe from violance while working.\n\nI want to reduce hazards that might cause injury to my customers.",
    "Trigger Words for Search": "Sensor\nVideo\nSecurity\nCrime\nHazard\nCustomers"
  },
  {
    "Industry": "Food Service\nRetail\nHotel/Motel\nProcess/Service\nAuto Service\nOffice/Professional\nHealth Care",
    "Vendor Name": "Floatbot",
    "Products": "Low-Code Chat Bot Building Tools",
    "Logo": "floatbot",
    "Web Link": "https://floatbot.ai/",
    "Description": "Floatbot is a conversational AI platform that helps businesses increase sales and reduce call volume by automating data collection and customer support, through (hybrid) AI-powered chatbots and voicebots.",
    "Contact Info": "Briane Stein\nPhone: (215) 987-4532",
    "Discount": "Nationwide customers will receive a 50% discount when deployed on at least two platforms.",
    "Example Scenarios": "I want my customers to be able to interact with my business digitally.\n\nI want to reduce call volume.\n\nI want to be able to service my customers after business hours.",
    "Trigger Words for Search": "Digital\nCalls\nService\nAvailable\nAutomate"
  }
]