export const vendors = [
  {
    "Industry": "Farm/Agribusiness",
    "vendor_name": "Quanturi",
    "product": "Grain Temperature Monitoring\nHay Temperature Monitoring\nCompost Temperature Monitoring",
    "Logo": "quanturi",
    "web_link": "https://quanturi.com/",
    "description": "Quanturi is the leading provider of wireless temperature monitoring and data analysis solutions for fermentable materials. Quanturi's robust systems are specifically designed to monitor hay, compost, grain and many other fermentable materials during storage. Quanturi systems help to reduce the risk of fire and support the quality control of stored materials.",
    "contact_info": "Name: John Anderson\nPhone: (612) 555-4321\nJanderson@quanturi.ai",
    "Discount": "5% hardware discount for Nationwide customers",
    "example_scenarios": "I am concerned about the risk of grain fires on my farm.\n\nIt is a challenge to control the quality of my hay while being stored.",
    "trigger_words_for_search": "Farm\nHay\nGrain\nFire\nQuality"
  },
  {
    "Industry": "Farm/Agribusiness",
    "vendor_name": "CropZilla",
    "product": "Farm Machine Analytics\nFarm Enterprise Software",
    "Logo": "cropzilla",
    "web_link": "https://cropzilla.com/",
    "description": "CropZilla uses sensor technology to track equipment performance, helping the farmer to optimize operations based on cost and timeliness.",
    "contact_info": "Name: Spencer Smith\nPhone: (330) 555-8557\nSpencers@cropzilla.com",
    "Discount": "Nationwide customers will receive a 20% discount on first year of software subscription",
    "example_scenarios": "It is difficult to understand where costs are being incurred on my farm.\n\nIt is difficult to project the cost of maintaining my farm in future years.",
    "trigger_words_for_search": "Farm\nCost\nMonitor\nControl\nDetect"
  },
  {
    "Industry": "Farm/Agribusiness\nFood Service\nHabitational\nHotel/Motel",
    "vendor_name": "OneEvent",
    "product": "Temperature Monitoring\nRefrigeration Monitoring",
    "Logo": "oneevent",
    "web_link": "https://oneeventtech.com/",
    "description": "OneEvent is a sensor technology solution that leverages machine learning to evaluate changes to the environment in which it is positioned. The product has been focused on the early detection of fire loss.",
    "contact_info": "Name: Chris Thomas\nPhone: (752) 651-4538\nThomas@oneevent.com",
    "Discount": "Nationwide customers will receive free installation on all OneEvent sensors",
    "example_scenarios": "I am interested in monitoring the sensors on my premises to make managing my business more streamlined.",
    "trigger_words_for_search": "Fire\nCooking\nBuilding"
  },
  {
    "Industry": "Food Service\nRetail\nHotel/Motel\nHabitational\nProcess/Service\nManufacturing\nAuto Service\nWholesale\nConstruction\nOffice/Professional\nHealth Care\nFarm/Agribusiness",
    "vendor_name": "HSB",
    "product": "IoT Commercial Sensor Solutions\nIoT Industrial Sensor Solutions\nIoT Residential Sensor Solutions",
    "Logo": "hsb",
    "web_link": "https://www.munichre.com/hsb/en.html",
    "description": "HSB can help avoid or reduce the damage to your building or equipment by detecting adverse conditions and then sending an alert, so the hazard can be mitigated prior to a loss.\n\nHSB sensors are ideal for detecting water leaks, frozen pipes, refrigeration failure, high temperature conditions, mold conditions, and power outages.",
    "contact_info": "Name: Zack Miller\nPhone: (651) 534-8324\nMiller@HSB.com",
    "Discount": "Nationwide customers will receive a 5% hardware discount equipment, along with free installation.",
    "example_scenarios": "I am concerned with monitoring my refrigeration systems within my convenience store.\n\nI am interested in monitoring power outages at my place of business while I am not present.",
    "trigger_words_for_search": "Refrigeration\nSystems\nPower\nSensor\nWater\nPipes\nTemperature"
  },
  {
    "Industry": "Farm/Agribusiness\nConstruction",
    "vendor_name": "Zubie",
    "product": "Asset Tracking\nDashcam",
    "Logo": "zubie",
    "web_link": "https://zubie.com/asset-trak/",
    "description": "Asset tracking that speeds the time to recover lost or stollen assets with previous locations, device tamper alerts, and location information. Detailed location history lets users monitor how and where assets are being used.",
    "contact_info": "Bob Mueller\nPhone: (568) 321-8537\nBM@Zubie.com",
    "Discount": "50% device discount for Nationwide customers",
    "example_scenarios": "I am interested in tracking my assets and associates as they manage my equipment.",
    "trigger_words_for_search": "Equipment\nMonitor\nTracking"
  },
  {
    "Industry": "Farm/Agribusiness\nFood Service\nHealth Care\nWholesale\nRetail",
    "vendor_name": "Razor Tracking",
    "product": "Asset Tracking\nVehicle Tracking,Dashcam",
    "Logo": "razortracking",
    "web_link": "https://razortracking.com/",
    "description": "Dash cameras developed to provide evidence of events leading up to and during road traffic accidents. The cameras provide instant notifications and video in less than a minute, allowing for driver coaching and assistance in claims handling.",
    "contact_info": "Joe Scarben\nPhone: (854) 555-8934\nScarben@razortracking.com",
    "Discount": "Nationwide customers will receive a 10% discount for participating in the Razor Tracking program.",
    "example_scenarios": "I am interested in tracking my assets and associates as they manage my business's vehicles and equipment.\n\nI want to be sure that my associates are driving safely.",
    "trigger_words_for_search": "Track\nSpeed\nVehicle\nEquipment\nAlert"
  },
  {
    "Industry": "Farm/Agribusiness\nHabitational\nFood Service\nHotel/Motel",
    "vendor_name": "PrevTech",
    "product": "Electrical Fire Detection",
    "Logo": "prevtech",
    "web_link": "https://www.prevtech.ca/",
    "description": "Prev Tech continuously monitors the condition of electrical networks, detecting and diagnosing abnormalities and potential problems in real time, allowing losses to be avoided entirely.",
    "contact_info": "Michael Burns\nPhone: (899) 551-4563\nMburns@prevtech.com",
    "Discount": "Nationwide customers will receive a 25% annual discount on software monitoring.",
    "example_scenarios": "I am interested in controlling the technology on my premises to manage my business in a more streamlined fashion.",
    "trigger_words_for_search": "Monitor\nElectrical\nEfficiency\nProblems"
  },
  {
    "Industry": "Farm/Agribusiness\nHabitational\nRetail\nFood Service",
    "vendor_name": "Ting",
    "product": "Electrical Fire Detection",
    "Logo": "ting",
    "web_link": "https://www.whiskerlabs.com/",
    "description": "Ting offers a unique and innovative approach to predict potentially hazardous conditions and help prevent disasters before they strike.",
    "contact_info": "Tim Martin\nPhone: (894) 546-1325\nTim.Martin@whiskerlabs.com",
    "Discount": "Nationwide customers will receive a 5% hardware discount.",
    "example_scenarios": "I am interested in controlling the technology on my premises to manage my business in a more streamlined fashion.",
    "trigger_words_for_search": "Property\nEfficiency\nMonitor"
  },
  {
    "Industry": "Farm/Agribusiness",
    "vendor_name": "BassAgritech Temprevent",
    "product": "Farm Machine Overheating Detection",
    "Logo": "bassagritech",
    "web_link": "https://www.bassagritech.com/temprevent",
    "description": "Temperature sensors detect overheating bearings or other components before any major issues can be caused. Sensors can fit in much tighter places and last longer than the most advanced temperature sensors currently on the market.",
    "contact_info": "Luke Allen\nPhone: (895)541-8974\nLAS@bassagritech.com",
    "Discount": "Nationwide customers will receive a 15% hardware discount and free installation.",
    "example_scenarios": "I am interested in avoiding the overheating of my equipment.\n\nI am concerned about machinery fires.",
    "trigger_words_for_search": "Machinery\nEquipment\nFire\nTemperature\nSensor"
  },
  {
    "Industry": "Farm/Agribusiness",
    "vendor_name": "Stripper Saver",
    "product": "Cotton Stripper Fire Suppression",
    "Logo": "strippersaver",
    "web_link": "https://www.facebook.com/Stripper-Saver-806-759-0649-735080730030510/",
    "description": "Fire suppression systems designed specifically for John Deere Cotton Strippers.",
    "contact_info": "Michael Gary\nPhone: (221) 891-5432\nMGary@Stripper-Saver.com",
    "Discount": "Nationwide customers will receive a 5% discount.",
    "example_scenarios": "I am interested in avoiding overheating of my equipment.\n\nI am concerned about machinery fires.",
    "trigger_words_for_search": "Fire\nStripper\nJohn Deere"
  },
  {
    "Industry": "Farm/Agribusiness\nManufacturing",
    "vendor_name": "Argus",
    "product": "Infrared Spark Detection\nFire Supression",
    "Logo": "argus",
    "web_link": "http://argusfirecontrol.com/product.html",
    "description": "Argus Fire Control specializes in the design, manufacture, and service of industrial production protection systems for fire hazards as well as metal detection and diverting. Argus Fire Control offers engineered systems for the textile spinning and non-woven industry as well as for wood-working, cotton gins, recycling, and other industrial applications.",
    "contact_info": "Owen Beckett\nPhone: (465) 548-5435\nOBP@ argusfirecontrol.com",
    "Discount": "Nationwide customers will receive a 20% discount on Argus hardware.",
    "example_scenarios": "I need assistance maintaining my production systems.\n\nI am interested in fire control of my industrial systems.",
    "trigger_words_for_search": "Fire\nIndustrial\nDetect\nManufacturing"
  },
  {
    "Industry": "Construction\nFarm/Agribusiness",
    "vendor_name": "ES Track",
    "product": "Asset Tracking\nVehicle Tracking\nDashcam\nFleet Management",
    "Logo": "estrack",
    "web_link": "https://www.equipmentshare.com/t3",
    "description": "ES Track offers telematics and hardware technology to monitor equipment health, software to optimize rental utilization, and mobile applications for team members to clock in and off on the spot. ES Track integrates with existing software systems to digitize a business's manual processes.",
    "contact_info": "Jacob Ryan\nPhone: (899)123-8452\nJR@equipmentshare.com",
    "Discount": "Nationwide customers will receive a 15% discount on hardware monitoring.",
    "example_scenarios": "I am interested in tracking my assets and associates as they manage my business's vehicles and equipment.",
    "trigger_words_for_search": "Vehicles\nEquipment\nSensor\nMonitor\nTrack"
  },
  {
    "Industry": "Food Service\nRetail\nHotel/Motel\nProcess/Service\nManufacturing\nAuto Service\nWholesale\nConstruction\nHealth Care\nFarm/Agribusiness",
    "vendor_name": "Kinetic",
    "product": "Wearable Injury Prevention",
    "Logo": "kinetic",
    "web_link": "https://www.wearkinetic.com/",
    "description": "Wearable devices and software that gather data and offer reminders to workers when the devices sense high-risk montions that could potentially cause injury.",
    "contact_info": "Walker Lane\nPhone: (944) 235-7788\nWalker@Kinetic.com",
    "Discount": "Nationwide customers will receive a 10% discount on Kinetic hardware.",
    "example_scenarios": "I want to make sure my employees are not injured.\n\nI want to be sure my business environment is safe for my workers.\n\nI want to make corrections to my facility that might cause injury.",
    "trigger_words_for_search": "Sensor\nWorker\nRisk\nMotion\nInjury"
  },
  {
    "Industry": "Manufacturing\nProcess/Service\nConstruction\nFarm/Agribusiness",
    "vendor_name": "MakUSafe",
    "product": "Wearable Injury Prevention",
    "Logo": "makeusafe",
    "web_link": "https://makusafe.com/?gclid=Cj0KCQiA5aWOBhDMARIsAIXLlkfnfBX6FZkNnPAPgq8J4DkIWSUFFts4Lav2d7ZSkQeGVY-KjAbig_0aApqIEALw_wcB",
    "description": "The MakUSafe dashboard displays data from connected factory equipment and systems, providing insights and context into employee health safety concerns. Devices send data from each worker to the business's platforms, creating opportunities to enhance operations and reduce workplace hazards.",
    "contact_info": "Sydney Kendall\nPhone: (635) 567-8922\nSydney@makusafe.com",
    "Discount": "Nationwide customers will receive hardware installation and training at no cost.",
    "example_scenarios": "I want to make sure my employees are not injured.\n\nI want to be sure my business environment is safe for my workers.\n\nI want to make corrections to my facility that might cause injury.",
    "trigger_words_for_search": "Sensor\nWorker\nRisk\nMotion\nInjury\nEnvironment"
  },
  {
    "Industry": "Habitational\nFarm/Agribusiness\nManufacturing\nConstruction",
    "vendor_name": "InfraLytiks",
    "product": "Data Analytics",
    "Logo": "infralytiks",
    "web_link": "https://infralytiks.com/",
    "description": "InfraLytiks is an engineering and data analytics company that uses machine learning, artificial intelligence, and computer vision to automate complex processes and detect internal building hazards.",
    "contact_info": "Gracelyn Hart\nPhone: (214) 321-7892\nGracelyn@infralytiks.com",
    "Discount": "Nationwide customers will receive a 10% discount on annual software monitoring.",
    "example_scenarios": "I want to detect the potential for fire inside my buildings.",
    "trigger_words_for_search": "Fire\nBuilding\nFarm"
  },
  {
    "Industry": "Habitational\nConstruction",
    "vendor_name": "Cape Analytics",
    "product": "Data Analytics",
    "Logo": "capeanalytics",
    "web_link": "https://capeanalytics.com/",
    "description": "Cape Analytics uses deep learning and geospatial imagery to provide instant property intelligence for buildings, including property defects and potential exposures.",
    "contact_info": "Cameron Beacher\nPhone: (863) 498-1235\nBeacher@capeanalytics.com",
    "Discount": "Nationwide customers will receive an annual 10% discount on software monitoring",
    "example_scenarios": "I want to avoid losses to my buildings.\n\nI want to detect problems that need to be fixed on my properties.",
    "trigger_words_for_search": "Imagery\nSatellite\nBuilding\nDamage\nHazard"
  },
  {
    "Industry": "Habitational\nFood Service\nRetail \nProcess Service\nOffice/Professional",
    "vendor_name": "Senseware",
    "product": "IoT Commercial Environment Sensor Monitoring",
    "Logo": "senseware",
    "web_link": "https://www.senseware.co/",
    "description": "Senseware is a wireless sensor-based system that communicates physical asset data on a real-time basis to help promote energy efficiency and sustainability. Senseware uses smart sensors, wireless communication, the internet, and cloud-based technology to ‘connect the unconnected’ and create Intelligent communities.",
    "contact_info": "Gia Mead\nPhone: (544)936-4512\nMead@senseware.co",
    "Discount": "Nationwide customers will receive free installation on all Senseware hardware.",
    "example_scenarios": "It is difficult to understand where costs are being incurred at my business.\n\nI am interested in monitoring the sensors on my premises to make managing my business more streamlined.",
    "trigger_words_for_search": "Sensor\nData\nMonitor\nEfficiency"
  },
  {
    "Industry": "Retail\nFood Service\nProfess/Service\nHabitational\nOffice/Professional",
    "vendor_name": "Deep Sentinel",
    "product": "Home Security Cameras",
    "Logo": "deepsentinel",
    "web_link": "https://www.deepsentinel.com/",
    "description": "Deep Sentinel is a home security company that produces a series of cameras powered by deep learning that can evaluate threats on a property.",
    "contact_info": "Peter Flynn\nPhone: (912) 453-7532\nFlynn@deepsentinel.com",
    "Discount": "Nationwide customers will receive free hardware and  one year of software monitoring.",
    "example_scenarios": "I want to be sure that my business is secure.\n\nI want to make sure my employees are safe from violence while working.",
    "trigger_words_for_search": "Sensor\nVideo\nSecurity\nCrime"
  },
  {
    "Industry": "Retail\nHotel/Motel\nProcess/Service\nAuto Service\nOffice/Professional",
    "vendor_name": "Cogito",
    "product": "AI coaching system for the contact center",
    "Logo": "cogito",
    "web_link": "https://cogitocorp.com/",
    "description": "Cogito enhances the emotional intelligence of phone professionals by applying behavioral science through artificial intelligence.",
    "contact_info": "Vick Ricky\nPhone: (744) 456-4211\nVick@Cogito.com",
    "Discount": "Nationwide customers will receive complimentary training and software monitoring on Cogito software.",
    "example_scenarios": "I want to be sure my employees are delivering the best customer experience possible.\n\nI want to help teach my employees how to be good customer service representatives.",
    "trigger_words_for_search": "Customer service\nMonitor\nTeach\nBehavior"
  },
  {
    "Industry": "Health Care\nHabitational",
    "vendor_name": "Care Predict",
    "product": "Wearable for Aged Care",
    "Logo": "carepredict",
    "web_link": "https://www.carepredict.com/",
    "description": "CarePredict technology continuously observes, learns, and triggers just in time care for aging seniors. The technology is ideal for group living, home care, and senior centers.",
    "contact_info": "Tom Townsie\nPhone: (894) 112-4882\nTownsie@carepredict.com",
    "Discount": "Nationwide customers will receive a 5% hardware discount, along with associate training.",
    "example_scenarios": "I want to take care of the patients at my facility.\n\nI want to help track the movements and locations of patients.\n\nI want to avoid patient and worker injury.",
    "trigger_words_for_search": "Senior care\nAssisted living\nNursing home\nPatients\nInjury\nTracking"
  },
  {
    "Industry": "Construction\nFood Service\nProcess/Service\nAuto Service\nHealth Care",
    "vendor_name": "Thimble",
    "product": "GIG Liability Insurance",
    "Logo": "thimble",
    "web_link": "https://www.thimble.com/",
    "description": "Thimble provides liability coverage for customers in more than 100 professions including landscapers, beauticians, dog walkers, handymen, DJs, and musicians. The flexible coverage platform offers short term, versatile insurance to small businesses, independent workers, and freelancers.",
    "contact_info": "Allen Wallace\nPhone: (112) 453-1232\nWallace@thimble.com",
    "Discount": "Nationwide customers will receive a 15% discount for bind within 24 hours.",
    "example_scenarios": "I want to purchase insurance for my small business.",
    "trigger_words_for_search": "Purchase\nProduct\nLiability\nPolicy"
  },
  {
    "Industry": "Food Service\nRetail\nHotel/Motel\nProcess/Service\nAuto Service\nOffice/Professional",
    "vendor_name": "ServiceBOT",
    "product": "Low-Code Chat Bot Building Tools",
    "Logo": "servicebot",
    "web_link": "https://servisbot.com/",
    "description": "A conversational AI platform that provides a number of low-code and no-code tools that enable business users to easily design, build, and manage conversational AI experiences.",
    "contact_info": "Jimmie Bond\nPhone: (235) 215-4621\nBond@ServiceBOT.com",
    "Discount": "Nationwide customers will receive a 20% discount when engaging to build BOT technology, bringing to production.",
    "example_scenarios": "I want my customers to be able to interact with my business digitally.\n\nI want to reduce call volume.\n\nI want to be able to service my customers after business hours.",
    "trigger_words_for_search": "Digital\nCalls\nService\nAvailable\nAutomate"
  },
  {
    "Industry": "Food Service\nRetail\nProcess/Service\nAuto Service\nConstruction\nHealth Care",
    "vendor_name": "Actuate",
    "product": "Computer Vision Hazard Detection",
    "Logo": "actuate",
    "web_link": "https://actuate.ai/",
    "description": "Actuate builds software that employs computer vision to automatically detect gun threats, intruders, and liability hazards in security camera feeds.",
    "contact_info": "Jessa Darrows\nPhone: (911) 546-4651\nDarrows@actuate.ai",
    "Discount": "Nationwide customers will receive a 15% discount on software monitoring.",
    "example_scenarios": "I want to be sure that my business is secure.\n\nI want to make sure my employees are safe from violence while working.\n\nI want to reduce hazards that might cause injury to my customers.",
    "trigger_words_for_search": "Sensor\nVideo\nSecurity\nCrime\nHazard\nCustomers"
  },
  {
    "Industry": "Food Service\nRetail\nHotel/Motel\nProcess/Service\nAuto Service\nOffice/Professional\nHealth Care",
    "vendor_name": "Floatbot",
    "product": "Low-Code Chat Bot Building Tools",
    "Logo": "floatbot",
    "web_link": "https://floatbot.ai/",
    "description": "Floatbot is a conversational AI platform that helps businesses increase sales and reduce call volume by automating data collection and customer support via (hybrid) AI-powered chatbots and voicebots.",
    "contact_info": "Briane Stein\nPhone: (215) 987-4532",
    "Discount": "Nationwide customers will receive a 50% discount when deployed on at least two platforms.",
    "example_scenarios": "I want my customers to be able to interact with my business digitally.\n\nI want to reduce call volume.\n\nI want to be able to service my customers after business hours.",
    "trigger_words_for_search": "Digital\nCalls\nService\nAvailable\nAutomate"
  }
]
